apiVersion: v2
name: lab-keycloak
description: Helm chart for experimenting with keycloak
type: application
version: 0.2.0
appVersion: "0.2.0"

dependencies:
  - name: postgres
    version: "0.2.0"
    repository: oci://ghcr.io/joeckr/charts
    alias: keycloak-db
    condition: postgres.enabled
