app:
  name: keycloak
  image: quay.io/keycloak/keycloak
  tag: 26.7.4
  pullPolicy: Always
  replicaCount: 1
  port: 8080
  admin:
    username: admin
    password: changeme # betterleaks:allow
  resources:
    limits:
      cpu: 6
      memory: 3Gi
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    fsGroup: 1031
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"

service:
  name: keycloak
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  name: keycloak-ingress
  host: "keycloak.joeckr.dev"
  className: "nginx"
  path: /
  pathType: "Prefix"

db:
  enabled: true
  postgres:
    name: keycloak-db
    tag: 18
    db: keycloak
    user: keycloak
    password: changeme # betterleaks:allow
