app:
  name: lab-keycloak
  image: quay.io/keycloak/keycloak
  tag: 26.7.4
  pullPolicy: Always
  replicaCount: 1
  port: 8080
  env: "lab"
  resources:
    limits:
      cpu: 6
      memory: 3Gi
    requests:
      cpu: 1200m
      memory: 896Mi
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"

service:
  name: lab-keycloak
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  name: lab-ingress
  host: "lab.local"
  route: "false"  # Set to "true" to generate an OpenShift Route instead of Ingress
  className: "nginx"
  path: /
  pathType: "Prefix"

postgres:
  enabled: true
  tag: 18
  db: keycloak
  user: keycloak
  password: changeme # betterleaks:allow
